### ISSUE TITLE
META: Move the codebase to typehints

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#1023]
This is a meta issue to keep track of the typehints move for the flow codebase.

- [x] Neos.Cache #1025
- [x] Neos.Eel #1022 
- [x] Neos.Error.Messages #945
- [x] Neos.Flow
  - [x] Neos.Flow.AOP+Cache #1041
  - [x] Neos.Flow.Cli+Command #1042
  - [x] Neos.Flow.Composer+Configuration+Core+Error #1043
  - [x] Neos.Flow.Utilities #1572
- [ ] Neos.FluidAdaptor
- [ ] Neos.Kickstarter
- [x] Neos.Utility.Arrays #946
- [x] Neos.Utility.Files #997
- [x] Neos.Utility.Lock #1026
- [x] Neos.Utility.MediaTypes #1000
- [x] Neos.Utility.ObjectHandling #1019
- [x] Neos.Utility.OpcodeCache #1015
- [x] Neos.Utility.Pdo #1016
- [x] Neos.Utility.Schema #1017
- [x] Neos.Utility.Unicode #1018

Breaking, on hold for next major:

- [x] Neos.Cache #991
- [x] Neos.Utility.Lock #999

**Comment by MarkusRodler** [comment]
#1065

**Comment by kdambekalns** [comment]
I guess this can be considered done.
