### ISSUE TITLE
Raise minimum supported PHP version to 7.3

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2236]
Since PHP 7.2 is EOL in November (https://www.php.net/supported-versions.php), we should phase out support for this version.

- [x] Remove 7.2 builds from travis (#2235)
- [x] Raise required PHP version in composer.json (#2237)
- [x] Adjust dependencies (#1880)
- [x] Adjust Neos (neos/neos-development-collection#3171 & neos/neos-development-collection#3172)
- [x] Update https://docs.neos.io/cms/installation-development-setup/system-requirements#php-version-matrix

We should also go forward with adding support for PHP 8 (see #2233)

**Comment by bwaidelich** [comment]
The docs still need to be adjusted: #2281
