### ISSUE TITLE
Finalize update to doctrine/migrations 3.0

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#2244]
- [x] adjust the DB migrations in Neos (the dev dist)
- [x] adjust the DB migrations in our other packages
  - [x] [neos/redirecthandler-databasestorage](https://github.com/neos/redirecthandler-databasestorage/tree/master/Migrations) – https://github.com/neos/redirecthandler-databasestorage/pull/26
  - [x] [neos/neos-googleanalytics](https://github.com/neos/neos-googleanalytics/tree/master/Migrations) - https://github.com/neos/neos-googleanalytics/pull/74
- [x] check everything works fine in more (real) projects
- [x] still different from before: output during migrations no longer shows what's happening. Need to figure out where the output goes (probably logger in the dependency factory needs to be populated and then read from)… #2328
- [x] go over CLI output in the documentation and update as needed… #2323
- [x] ~when a property has been removed from a model, `cache:flush` needs to be run to avoid an error (see below)~ -> #2336

_Originally posted by @kdambekalns in https://github.com/neos/flow-development-collection/issues/1880#issuecomment-726137105_

**Comment by kdambekalns** [comment]
https://github.com/neos/flow-development-collection/issues/2244

**Comment by kdambekalns** [comment]
@albe With "in our other packages" I meant  things _not_ pulled in with the dev distribution… Things like the redirect handler and similar packages…

**Comment by bwaidelich** [comment]
When I executed `./flow doctrine:migrate` in a local test project of mine that already had migrations, I got an error
```
An exception occurred while executing 'RENAME TABLE typo3_flow_mvc_routing_objectpathmapping TO neos_flow_mvc_routing_objectpathmapping':
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'neos_flow_mvc_routing_objectpathmapping' already exists
```
And the `flow_doctrine_migrationstatus` now has both, the old `<Version>` entries and the new ones with the FQN.

My bad because I didn't read the instructions and apparently I should have executed `./flow doctrine:migrationstatus` first. But I'm sure I won't be the only one so maybe
* We can tweak the `doctrine:migrate` command such that it checks existing migrations and/or
* Provide another command that fixes the issue (reverting the structural changes to `flow_doctrine_migrationstatus`, removing the new entries and fixing it properly)

**Comment by bwaidelich** [comment]
@kdambekalns sorry for the ping, but can you already estimate when this is finalized? I assume that the remaining tasks are required for a stable major release, right?

**Comment by kdambekalns** [comment]
Hopefully this week! 😬

**Comment by bwaidelich** [comment]
@kdambekalns I'm currently thinking about an escape hatch in case we can't finalize this one until.. well.. tomorrow. Would it be an option to revert already merged PRs and re-apply them on the master branches or is that a no-go?

**Comment by kdambekalns** [comment]
Ouch. Well. That means waiting until 8.0?

From my POV the only thing that really needs to be addressed is making our (other) packages compatible. The CLI output can be fixed later, as can the documentation. Both are important, but not worth delaying this another year.

Also, what is tomorrow? 08:00 or 20:00 CET? 😬

**Comment by bwaidelich** [comment]
@kdambekalns Thanks for the update!

> Also, what is tomorrow? 08:00 or 20:00 CET?

8pm.. _seven days ago_ :)
No, if we can tag the release by tomorrow evening I'll cut capers. It would be great to have it done for the upcoming Neos Meetup (on Wednesday).

I'm happy to help with making our other packages compatible, if you can coordinate myself a little :)

Also I would like to "fix" the initial `doctrine:migrate` call that currently skips the "migration migration" step I think. But it should be fairly easy to get that a little more stable

**Comment by kdambekalns** [comment]
> Also I would like to "fix" the initial `doctrine:migrate` call that currently skips the "migration migration" step I think.

I tried that, and it works as expected with ´migrationstatus` as well as `migrate`. As is to be expected, since the code flow in Doctrine Migrations is the same for anything that accesses the migration status storage.

I think it's a problem only when non-migrated migrations are present, then the process dies right in the middle and leaves a broken state behind (not all entries migrated, but the storage table structure already changed, thus the adjustment never kicks in again…)

**Comment by kdambekalns** [comment]
Yes, but it depends on the kind of error:

- with a migration that has not been updated and still extends `Doctrine\DBAL\Migrations\AbstractMigration` execution halts with `Class 'Doctrine\DBAL\Migrations\AbstractMigration' not found` and the storage remains unchanged (good!)
- with a migration that has not been updated and has mismatching method signatures on `up()`, `down()` or any other method, execution halts with a PHP fatal error  and the storage remains unchanged (good!)
- if a migration dies while it is actually run, the state is left broken (bad!)

The latter will not happen with `doctrine:migrationstatus`, since no method on the migration is actually called, so it's a "safe" way of updating the storage.

**Comment by kdambekalns** [comment]
And now I wanted to create a corresponding issue with the Migrations project and **can no longer reproduce** a broken metadata storage… 🤯

**Comment by bwaidelich** [comment]
I still get stuck trying to upgrade a 5.3 Neos project.
```
./flow doctrine:migrate
```
failed because already applied migrations were applied again (I just wanted to test that this is still the case). Afterwards I removed all new `flow_doctrine_migrationstatus` entries (those with namespaces) and ran
```
./flow doctrine:migrationstatus
```
which gives me
```
+----------------------+-------------------------------------------+------------------------------------------------------------------------+
| Configuration                                                                                                                             |
+----------------------+-------------------------------------------+------------------------------------------------------------------------+
| Storage              | Type                                      | Doctrine\Migrations\Metadata\Storage\TableMetadataStorageConfiguration |
|                      | Table Name                                | flow_doctrine_migrationstatus                                          |
|                      | Column Name                               | version                                                                |
|-------------------------------------------------------------------------------------------------------------------------------------------|
| Database             | Driver                                    | Doctrine\DBAL\Driver\PDO\MySQL\Driver                                  |
|                      | Name                                      | cornelsen_de_neos70                                                    |
|-------------------------------------------------------------------------------------------------------------------------------------------|
| Versions             | Previous                                  | 20201020110645                                                         |
|                      | Current                                   | 20201109140652                                                         |
|                      | Next                                      | Neos\Flow\Persistence\Doctrine\Migrations\Version20110613223837        |
|                      | Latest                                    | Neos\Flow\Persistence\Doctrine\Migrations\Version20201109140652        |
|-------------------------------------------------------------------------------------------------------------------------------------------|
| Migrations           | Executed                                  | 170                                                                    |
|                      | Executed Unavailable                      | 170                                                                    |
|                      | Available                                 | 172                                                                    |
|                      | New                                       | 172                                                                    |
|-------------------------------------------------------------------------------------------------------------------------------------------|
| Migration Namespaces | Neos\Flow\Persistence\Doctrine\Migrations | /Users/bwaidelich/Websites/cornelsen.de-neos7/Data/DoctrineMigrations  |
+----------------------+-------------------------------------------+------------------------------------------------------------------------+
```

but doesn't "fix" existing records

**Comment by bwaidelich** [comment]
Ah, found it.. It wasn't enough to remove new entries from the migration table, I had to revert the structure change and afterwards doctrine will apply the upgrade.
I try to improve the DX in this part

**Comment by kdambekalns** [comment]
> It wasn't enough to remove new entries from the migration table

Exactly! But WHY does it apply migrations again? Are you sure your table wasn't broken from some earlier mishap? And even with such errors, it shoould upgrade the metadata storage just fine… 🤨

**Comment by bwaidelich** [comment]
> Are you sure your table wasn't broken from some earlier mishap?

Mh.. Not 100% sure. But it might have been some unflushed cache.. At least I can't reproduce this any longer (reset table to old structure & content, run `doctrine:migrate` => works)

**Comment by bwaidelich** [comment]
> At least I can't reproduce this any longer
too soon.. I _can_ reproduce it

**Comment by bwaidelich** [comment]
reason seems to be an SQL error that occurs during migration, is swallowed(!) and stops the migration migration half way..
In my case:
```
An exception occurred while executing 'ALTER TABLE neos_flow_resourcemanagement_persistentresource DROP md5'
```
and that seems to come from re-applying an already migrated version

**Comment by bwaidelich** [comment]
=> #2333

**Comment by kdambekalns** [comment]
> and that seems to come from re-applying an already migrated version

But… first the versions are updated. Then read and applied, if needed. If it's alredy applied and fixed, it won't happen again. If the update doesn't fix the versions, leading to this being applied again, the error cannot be the cause for the update not having suceeded…

**Comment by bwaidelich** [comment]
@kdambekalns I think you can reproduce it by removing a record from the migrations table

**Comment by kdambekalns** [comment]
I tried that, and even though it broke, the metadata was updated just fine. 🤷‍♂️

**Comment by bwaidelich** [comment]
FYI: I'll take care of https://github.com/neos/neos-googleanalytics

**Comment by bwaidelich** [comment]
@kdambekalns once https://github.com/neos/neos-googleanalytics/pull/74 and https://github.com/Flowpack/Flowpack.GoogleApiClient/pull/2 are merged & tagged, can we close this one and move the last todo into a bug issue?
