### ISSUE TITLE
Smooth upgrade for Component- to Middleware chain

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#2258]
### Description

With #2019 core HTTP components will be converted to the middleware chain and with #2221 the HTTP component infrastructure is being removed from Flow.

We should

- [x] Document the new middleware implementation (#2308)
- [x] Document how to migrate existing packages/components (#2330)
- [x] Provide a Core Migration that can detect (and partly migrate?) HTTP components (#2315 & #2320)
- [x] ~Potentially detect `Neos.Flow.http.chain` configuration and throw a helpful exception in order to prevent subtle bugs to creep in (#2306)~ (we agreed that a proper detection/core migration would be better)
- [x] Provide CLI command that lists all configured middleware components in the correct order (#2307)

**Comment by albe** [comment]
@bwaidelich regarding the "Document how to migrate existing packages/components" - where should we document that? Only in the release notes on neos.io? Or as part of the PR message for the generated release notes?

**Comment by bwaidelich** [comment]
I think a good start would be examples of at least two different kinds of middleware.
Then we could link to those from the release notes and the PR saying sth like

```php
$componentContext->replaceHttpResponse($componentContext->getHttpResponse()->withAddedHeader('X-Foo', 'bar');
```
=> This is how you tweak the response now

```php
$componentContext->replaceHttpResponse($newResponse);
$componentContext->setParameter(ComponentChain::class, 'cancel', true);
```

=> This is how you replace the response now

```php
$componentContext->setParameter(...)
```

=> This is how you communicate with other mw components now
