### ISSUE TITLE
META: Cleanup behat stuff

### ISSUE THREAD

**Issue by mhsdesign** [neos/flow-development-collection#3169]
- [x] revert hack https://github.com/neos/neos-ui/pull/3569/commits/103afcf25ed28a65eebe7c69fddbfc63f7f163d7
- [x] revert hack https://github.com/neos/redirecthandler-neosadapter/pull/60/files/892f8a4e6b618d935c709103cd6ebdf5253eb504#r1354586677
- [x] https://github.com/neos/flow-development-collection/pull/3175
- [x] https://github.com/neos/flow-development-collection/pull/3173
- [x] https://github.com/neos/neos-development-collection/pull/4543
- [x] https://github.com/neos/neos-development-collection/pull/4544 (cleans up also behat stuff partially)
- [x] https://github.com/neos/behat/pull/35
- [x] https://github.com/neos/neos-development-collection/pull/4669
- [x] https://github.com/neos/neos-development-collection/pull/4669

public usages that we need to consider:

`FlowContextTrait` in every package that has behat tests:

- `Flowpack.DecoupledContentStore`
- `Neos.RedirectHandler.NeosAdapter`

### Packages using "scarier" functionality:

`SecurityOperationsTrait` in https://github.com/Flowpack/Flowpack.DecoupledContentStore/blob/6adb8e04246f5fc9b8471b656db7ddf131474745/Tests/Behavior/Features/Bootstrap/FeatureContext.php#L49 -> requires `$isolated = false`

And a lot of better to be cleaned up stuff in the `Neos.RedirectHandler.NeosAdapter` version 9

### Utility package for actual e2e tests based up on neos e2e "api"

- https://github.com/sandstorm/Sandstorm.E2ETestTools

- https://github.com/cron-eu/neos-behat/blob/cf5628722862373783827bd513d2f5af4413f524/Tests/Behat/FeatureContextBase.php#L30

**Comment by mhsdesign** [comment]
The last open task is to get rid of our `@isolated` stuff but thats for another time. https://github.com/neos/flow-development-collection/issues/3170

Our behat things are now cleaned up ^^
